[package]
name = "generic_traits_lifetime"
version = "0.1.0"
authors = ["mfc <cristian.marius.florin@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
